export const FORM_CHANGE_NAME_TEXT = 'FORM_CHANGE_NAME_TEXT',
             FORM_CHANGE_NUMBER_TEXT = 'FORM_CHANGE_NUMBER_TEXT',
             FORM_RESET_STATE = 'FORM_RESET_STATE',
             APP_ADD_ID_STATE = 'APP_ADD_ID_STATE',
             APP_SET_DATA_STATE = 'APP_SET_DATA_STATE',
             APP_SET_DATA_ARR_STATE = 'APP_SET_DATA_ARR_STATE'